import React from "react";
import {
  Search,
  SearchX,
  X,
  Menu,
  Home,
  MapPin,
  MapPinPlus,
  Store,
  Newspaper,
  Calendar,
  Clock,
  Filter,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ChevronLeft,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowUpDown,
  Eye,
  EyeOff,
  Edit3,
  Trash2,
  Plus,
  PlusCircle,
  Minus,
  MinusCircle,
  Check,
  CheckCircle2,
  CheckCheck,
  ClipboardCheck,
  Info,
  AlertTriangle,
  AlertCircle,
  Upload,
  UploadCloud,
  Download,
  Share2,
  Phone,
  Mail,
  Link as LinkIcon,
  RefreshCw,
  User,
  UserPlus,
  UserCheck,
  UserX,
  UserMinus,
  Users,
  Settings,
  SlidersHorizontal,
  LayoutDashboard,
  Network,
  LogOut,
  LogIn,
  Send,
  Bookmark,
  Target,
  Flag,
  Image as ImageIcon,
  ImagePlus,
  FileImage,
  Images,
  Map as MapIcon,
  Layers,
  Star,
  Lock,
  Key,
  KeyRound,
  Shield,
  ShieldCheck,
  ShieldAlert,
  GraduationCap,
  Building2,
  Building,
  Landmark,
  Leaf,
  Sprout,
  Trees,
  Fish,
  Mountain,
  Theater,
  Wrench,
  Package,
  ShoppingBag,
  Camera,
  MessageSquare,
  Globe,
  Contact,
  ExternalLink,
  Navigation,
  LocateFixed,
  TrendingUp,
  HeartPulse,
  FileEdit,
  FileText,
  FileCheck,
  FileSearch,
  FileCode,
  FilePlus,
  FileWarning,
  Quote,
  Mic,
  Scroll,
  History,
  Megaphone,
  Minimize2,
  MoveHorizontal,
  Folder,
  FolderOpen,
  Tag,
  BadgePercent,
  Activity,
  BarChart2,
  Sparkles,
  Lightbulb,
  Flame,
  HelpCircle,
  Copy,
  Zap,
  MousePointerClick,
  MousePointer,
  Compass,
  QrCode,
  Bell,
  Database,
  Server,
  HardDrive,
  CircleDot,
  MoreVertical,
  MoreHorizontal,
  LucideProps,
} from "lucide-react";
import { cn } from "@/shared/utils/cn";

interface IconProps {
  /** Icon name ligature, e.g. "search", "storefront", "calendar_today". */
  name: string;
  className?: string;
  /** Kept for backwards compatibility with legacy Material Symbols filled prop. */
  filled?: boolean;
}

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Navigation & Directional
  search: Search,
  search_off: SearchX,
  search_globe: Globe,
  close: X,
  cancel: X,
  clear: X,
  menu: Menu,
  home: Home,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_right_alt: ArrowRight,
  arrow_outward: ArrowUpRight,
  arrow_up_right: ArrowUpRight,
  arrow_up_down: ArrowUpDown,
  sort: ArrowUpDown,
  expand_more: ChevronDown,
  keyboard_arrow_down: ChevronDown,
  expand_less: ChevronUp,
  keyboard_arrow_up: ChevronUp,
  open_in_new: ExternalLink,
  external_link: ExternalLink,
  directions: Navigation,
  navigation: Navigation,
  my_location: LocateFixed,
  location_searching: LocateFixed,
  gps_fixed: LocateFixed,
  locate: LocateFixed,
  swipe: MoveHorizontal,
  move_horizontal: MoveHorizontal,
  compass: Compass,
  travel_explore: Globe,

  // Action & Edit
  edit: Edit3,
  edit_note: Edit3,
  edit_square: FileEdit,
  edit_document: FileEdit,
  document: FileText,
  file_text: FileText,
  file_edit: FileEdit,
  file_search: FileSearch,
  file_code: FileCode,
  file_plus: FilePlus,
  file_warning: FileWarning,
  delete: Trash2,
  delete_forever: Trash2,
  add: Plus,
  plus: Plus,
  add_circle: PlusCircle,
  remove: Minus,
  minus: Minus,
  remove_circle: MinusCircle,
  check: Check,
  check_circle: CheckCircle2,
  check_circle2: CheckCircle2,
  check_check: CheckCheck,
  double_check: CheckCheck,
  task_alt: CheckCircle2,
  verified: CheckCircle2,
  verified_user: ShieldCheck,
  assignment_turned_in: ClipboardCheck,
  send: Send,
  upload: Upload,
  upload_file: Upload,
  cloud_upload: UploadCloud,
  upload_cloud: UploadCloud,
  compress: Minimize2,
  minimize: Minimize2,
  download: Download,
  share: Share2,
  link: LinkIcon,
  sync: RefreshCw,
  refresh: RefreshCw,
  save: FileEdit,
  format_quote: Quote,
  quote: Quote,
  login: LogIn,
  log_in: LogIn,
  logout: LogOut,
  log_out: LogOut,
  copy: Copy,
  content_copy: Copy,
  file_copy: Copy,
  bolt: Zap,
  zap: Zap,
  flash: Zap,
  touch_app: MousePointerClick,
  pointer: MousePointerClick,
  mouse_pointer: MousePointer,
  mouse_pointer_click: MousePointerClick,

  bookmark: Bookmark,
  target: Target,
  flag: Flag,
  eco: Leaf,
  insights: TrendingUp,
  trending_up: TrendingUp,
  activity: Activity,
  sparkles: Sparkles,
  lightbulb: Lightbulb,
  flame: Flame,
  popular: Flame,

  // Media & View
  visibility: Eye,
  eye: Eye,
  visibility_off: EyeOff,
  eye_off: EyeOff,
  image: ImageIcon,
  photo: ImageIcon,
  add_a_photo: Camera,
  add_photo_alternate: ImagePlus,
  collections: Images,
  photo_library: Images,
  images: Images,
  file_image: FileImage,
  newspaper: Newspaper,
  article: Newspaper,

  // Location & Places
  location_on: MapPin,
  pin_drop: MapPin,
  place: MapPin,
  location: MapPin,
  pin: MapPin,
  edit_location_alt: MapPinPlus,
  edit_location: MapPinPlus,
  map: MapIcon,
  storefront: Store,
  store: Store,
  layers: Layers,
  location_city: Landmark,
  account_balance: Landmark,
  landmark: Landmark,

  // Medical & Health
  kesehatan: HeartPulse,
  medical_services: HeartPulse,
  local_hospital: HeartPulse,
  hospital: HeartPulse,
  health_and_safety: HeartPulse,
  healing: HeartPulse,
  posyandu: HeartPulse,
  puskesmas: HeartPulse,

  // Education & School
  pendidikan: GraduationCap,
  school: GraduationCap,
  local_library: GraduationCap,
  menu_book: GraduationCap,
  education: GraduationCap,
  sekolah: GraduationCap,

  // Religion & Government
  ibadah: Building,
  mosque: Building,
  church: Building,
  place_of_worship: Building,
  kantor_desa: Building2,
  pemerintahan: Building2,
  balai_desa: Building2,
  building: Building,
  building2: Building2,
  history_edu: Scroll,
  history: History,
  scroll: Scroll,
  record_voice_over: Mic,
  campaign: Megaphone,
  megaphone: Megaphone,

  // Potensi & Agriculture
  agriculture: Sprout,
  pertanian: Sprout,
  grass: Sprout,
  forest: Trees,
  perkebunan: Trees,
  park: Trees,
  nature: Trees,
  pets: HeartPulse,
  peternakan: HeartPulse,
  set_meal: Fish,
  perikanan: Fish,
  landscape: Mountain,
  pariwisata: Mountain,
  wisata: Mountain,
  attractions: Landmark,
  tourist_attraction: Landmark,
  theater_comedy: Theater,
  kebudayaan: Theater,
  handyman: Wrench,
  kerajinan: Wrench,
  build: Wrench,
  inventory_2: Package,
  shopping_bag: ShoppingBag,
  package: Package,
  tag: Tag,
  discount: BadgePercent,

  // Info & Status
  info: Info,
  info_outline: Info,
  help: HelpCircle,
  help_outline: HelpCircle,
  question: HelpCircle,
  question_mark: HelpCircle,
  warning: AlertTriangle,
  gavel: AlertTriangle,
  error: AlertCircle,
  star: Star,
  lock: Lock,
  key: Key,
  vpn_key: Key,
  key_round: KeyRound,
  shield: Shield,
  shield_check: ShieldCheck,
  shield_alert: ShieldAlert,
  admin_panel_settings: ShieldCheck,
  pending_actions: Clock,
  bell: Bell,
  notifications: Bell,
  qr_code: QrCode,
  qrcode: QrCode,

  // People & User
  user: User,
  person: User,
  person_outline: User,
  account_circle: User,
  person_add: UserPlus,
  user_x: UserX,
  user_minus: UserMinus,
  group: Users,
  groups: Users,
  people: Users,
  family_restroom: Users,
  assignment_ind: UserCheck,

  // Communication & Social
  chat: MessageSquare,
  message: MessageSquare,
  phone: Phone,
  call: Phone,
  email: Mail,
  mail: Mail,
  contact_mail: Contact,
  language: Globe,
  public: Globe,
  globe: Globe,

  // Date & Time
  calendar_today: Calendar,
  calendar: Calendar,
  event: Calendar,
  schedule: Clock,
  clock: Clock,

  // System & Admin
  filter_list: Filter,
  filter: Filter,
  filter_alt: Filter,
  tune: SlidersHorizontal,
  sliders: SlidersHorizontal,
  sliders_horizontal: SlidersHorizontal,
  settings: Settings,
  dashboard: LayoutDashboard,
  schema: Network,
  folder: Folder,
  folder_open: FolderOpen,
  chart: BarChart2,
  database: Database,
  server: Server,
  hard_drive: HardDrive,
  more_vert: MoreVertical,
  more_vertical: MoreVertical,
  more_horiz: MoreHorizontal,
  more_horizontal: MoreHorizontal,
};

/**
 * High-performance Lucide React Icon wrapper.
 * Replaces Material Symbols Webfont with lightweight inline SVGs.
 */
export function Icon({ name, className, filled = false }: IconProps) {
  const normalizedKey = (name || "").toLowerCase().trim().replace(/[- ]/g, "_");
  let IconComponent = ICON_MAP[normalizedKey] || ICON_MAP[name];

  if (!IconComponent) {
    // Contextual smart fallback to guarantee NO unexpected "?" question marks appear
    if (normalizedKey.includes("help") || normalizedKey.includes("question")) {
      IconComponent = HelpCircle;
    } else if (normalizedKey.includes("check") || normalizedKey.includes("success") || normalizedKey.includes("verified")) {
      IconComponent = CheckCircle2;
    } else if (normalizedKey.includes("error") || normalizedKey.includes("alert") || normalizedKey.includes("fail") || normalizedKey.includes("danger")) {
      IconComponent = AlertCircle;
    } else if (normalizedKey.includes("user") || normalizedKey.includes("person") || normalizedKey.includes("account")) {
      IconComponent = User;
    } else if (normalizedKey.includes("file") || normalizedKey.includes("doc") || normalizedKey.includes("text")) {
      IconComponent = FileText;
    } else if (normalizedKey.includes("image") || normalizedKey.includes("photo") || normalizedKey.includes("picture")) {
      IconComponent = ImageIcon;
    } else if (normalizedKey.includes("map") || normalizedKey.includes("pin") || normalizedKey.includes("loc")) {
      IconComponent = MapPin;
    } else if (normalizedKey.includes("key") || normalizedKey.includes("lock") || normalizedKey.includes("pass") || normalizedKey.includes("auth")) {
      IconComponent = Lock;
    } else if (normalizedKey.includes("search") || normalizedKey.includes("find")) {
      IconComponent = Search;
    } else if (normalizedKey.includes("copy")) {
      IconComponent = Copy;
    } else if (normalizedKey.includes("zap") || normalizedKey.includes("bolt") || normalizedKey.includes("flash")) {
      IconComponent = Zap;
    } else if (normalizedKey.includes("arrow") || normalizedKey.includes("next")) {
      IconComponent = ArrowRight;
    } else {
      // Safe, neutral icon without rendering a question mark
      IconComponent = CircleDot;
    }
  }

  return (
    <IconComponent
      className={cn(
        "inline-block shrink-0 transition-colors",
        filled && "fill-current",
        className,
      )}
      aria-hidden="true"
    />
  );
}
